### ISSUE TITLE
Viability on non-Apple platforms

### ISSUE THREAD

**Issue by mickeyl** [p-x9/AssociatedObject#17]
Naturally this only works on platforms where Swift is backed by an Objective-C runtime. I wonder how we could extend this to other platforms where this isn‘t available, perhaps using a global in memory storage area?

**Comment by p-x9** [comment]
Indeed, due to the dependency on ObjectiveC, the build was failing on Linux.

https://swiftpackageindex.com/p-x9/AssociatedObject/builds

The basic implementation by Apple of associatedObject is found in the following.

https://github.com/apple-oss-distributions/objc4/blob/689525d556eb3dee1ffb700423bccf5ecc501dbf/runtime/objc-references.mm

A similar implementation might allow for similar functionality outside of the Apple platform.

**Comment by p-x9** [comment]
Hello, @mickeyl 
It's been some time, but I just created a library of Associated object that can work on Linux and other platforms.

https://github.com/p-x9/swift-object-association

I would like to consider including its introduction to this `AssociatedObject` Macro in the future.

**Comment by p-x9** [comment]
Supported in version [0.10.0](https://github.com/p-x9/AssociatedObject/releases/tag/0.10.0)
